export const PHASE_DURATION_S = 4;
export const CYCLE_DURATION_S = PHASE_DURATION_S * 4;

export const TRANSLATIONS = {
  ru: {
    inhale: "Вдох",
    holdIn: "Задержка",
    exhale: "Выдох",
    holdOut: "Задержка",
    start: "Начать",
    stop: "Стоп",
    selectDuration: "Выберите длительность",
    min: "мин",
    cycles: "циклы",
    sessions: "сессий",
    totalCycles: "всего циклов",
    stats: "Статистика",
    close: "Закрыть",
    title: "Квадратное дыхание",
    description: "Ритмичное дыхание по схеме 4-4-4-4 для повышения концентрации и устойчивости к стрессу.",
    toggleLanguage: "Переключить язык",
    toggleSound: "Переключить звук",
    toggleTheme: "Переключить тему",
  },
  en: {
    inhale: "Inhale",
    holdIn: "Hold",
    exhale: "Exhale",
    holdOut: "Hold",
    start: "Start",
    stop: "Stop",
    selectDuration: "Select duration",
    min: "min",
    cycles: "cycles",
    sessions: "sessions",
    totalCycles: "total cycles",
    stats: "Statistics",
    close: "Close",
    title: "Box Breathing",
    description: "A 4-4-4-4 rhythmic breathing technique to enhance focus and stress resistance.",
    toggleLanguage: "Toggle language",
    toggleSound: "Toggle sound",
    toggleTheme: "Toggle theme",
  }
};